### ISSUE TITLE
how to make it dynamic?

### ISSUE THREAD

**Issue by pankti-fadia-inferenz** [alperenuzun/basic-virtual-tryon-glasses#1]
I am trying to apply different glasses but they do not fit properly. so where do I have to do the changes?

**Comment by alperenuzun** [comment]
Hi @Pankti-Fadia, this repo was an experiment for me to get practice in AR as a hobby, so did not dig down into details in the code base. If you would like to use another glasses by the different scales and positions, unfortunately you should adjust the base position, scale and rotation of the glasses according to your needs. So, you should create all of your glasses in the same position and lengths in the space coordinates. Also you should put the middle position of glasses at 0, 0, 0 point.

Another way is that you can use the obj and mtl files from `public/obj` folder in your 3D design program.

Actually, I would like to make it dynamically adjustable If I have the time but impossible for now. If you would like to contribute the project, I would be happy for that.

**Comment by pankti-fadia-inferenz** [comment]
Yes, Thanks. I will try that.
